version: 2.1

orbs:
  kube: circleci/kubernetes@1.3.0

jobs:
  deploy:
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout
      - kube/install-kubectl
      - kube/install-kubeconfig
      - setup_remote_docker
      - run:
          name: Authenticate on DockerHub
          command: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
      - run:
          name: Fix the version for the docker and kubernetes executions
          command: echo "export DOCKER_TAG=$(date +%s)" >> $BASH_ENV
      - run:
          name: Build the image to be able to push it online
          command: docker build -t virtuatable/gui-webserver:${DOCKER_TAG} -f deployment/Dockerfile .
      - run:
          name: Push the image to the DockerHub DTR
          command: docker push virtuatable/gui-webserver:${DOCKER_TAG}
      - run:
          name: Deploys the application on Kubernetes
          command: sed -e "s/<VERSION>/${DOCKER_TAG}/g" deployment/deployment.yml | kubectl apply -f -
      - run:
          name: Creates the application load balancer
          command: kubectl apply -f deployment/service.yml
      - run:
          name: Creates the ingress to access the app
          command: kubectl apply -f deployment/ingress.yml

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master