apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: gui
  name: gui-webserver-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: gui-webserver
spec:
  rules:
    - http:
        paths:
          - path: "/gui(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: 80